import { SiteNav } from '../components/SiteNav'
import { SiteFooter } from '../components/SiteFooter'

const accent = 'var(--accent)'
const muted = 'var(--text-muted)'
const dim = 'var(--text-dim)'
const border = 'var(--border)'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '2.5rem' }}>
      <p style={{ fontFamily: 'DM Mono, monospace', fontSize: '0.62rem', letterSpacing: '0.18em', textTransform: 'uppercase', color: accent, marginBottom: '1rem' }}>
        {title}
      </p>
      <div style={{ borderTop: `1px solid ${border}`, paddingTop: '1.2rem' }}>
        {children}
      </div>
    </div>
  )
}

const body: React.CSSProperties = {
  fontFamily: 'DM Mono, monospace',
  fontSize: '0.78rem',
  color: muted,
  lineHeight: 1.85,
}

const h2: React.CSSProperties = {
  fontFamily: 'Instrument Serif, Georgia, serif',
  fontSize: '1.2rem',
  color: accent,
  fontWeight: 400,
  marginBottom: '1.5rem',
  marginTop: '3.5rem',
}

export function Terms() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)' }}>
      <SiteNav />

      <div style={{ maxWidth: 600, margin: '0 auto', padding: '8rem 2rem 6rem' }}>

        <p style={{ fontFamily: 'DM Mono, monospace', fontSize: '0.6rem', letterSpacing: '0.15em', textTransform: 'uppercase', color: dim, marginBottom: '0.6rem' }}>
          Last updated June 2026
        </p>
        <h1 style={{ fontFamily: 'Instrument Serif, Georgia, serif', fontSize: '1.6rem', color: accent, fontWeight: 400, marginBottom: '0.75rem', lineHeight: 1.2 }}>
          Terms &amp; Data
        </h1>
        <p style={{ ...body, marginBottom: '3rem' }}>
          These terms govern your use of alvirassa. By using the service, you accept them.
        </p>

        {/* TERMS AND CONDITIONS */}
        <h2 style={h2}>Terms and Conditions</h2>

        <Section title="The service">
          <p style={body}>
            alvirassa is a structural observation system. You submit observations — descriptions of things that deviate structurally from what their context predicts — and the system scores, stores, and compares them across domains within your case.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            The service is provided as-is. We do not guarantee availability, completeness of analysis, or fitness for any particular investigative purpose. The system generates hypotheses based on structural correspondence; these are analytical outputs, not conclusions or professional advice of any kind.
          </p>
        </Section>

        <Section title="Your use">
          <p style={body}>
            You are responsible for what you submit. You may not use alvirassa to process information you are not authorized to handle, to attempt to identify individuals without their consent, or for any purpose that is unlawful in your jurisdiction.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            Each case is controlled by its access code. You are responsible for keeping that code secure. We cannot recover access to a case if the code is lost.
          </p>
        </Section>

        <Section title="Intellectual property">
          <p style={body}>
            The observations you submit remain yours. You grant us the right to store and process them to operate the service and, in aggregate and anonymized form, to improve the system. We do not claim ownership of your work.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            The alvirassa system — its frameworks, scoring methodology, hypothesis generation logic, and interface — is our intellectual property.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p style={body}>
            alvirassa is a tool for structural observation. It does not provide legal, medical, financial, or professional advice. We are not liable for decisions made on the basis of hypotheses or outputs generated by the system.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            To the extent permitted by law, our liability for any claim arising from use of the service is limited to the amount you paid us in the three months preceding the claim.
          </p>
        </Section>

        <Section title="Changes and termination">
          <p style={body}>
            We may update these terms. Continued use after a change constitutes acceptance. We may suspend or discontinue the service with reasonable notice. If we discontinue, we will provide a way to export your case data for a period of at least 30 days.
          </p>
        </Section>

        {/* PRIVACY POLICY */}
        <h2 style={h2}>Privacy Policy</h2>

        <Section title="What we collect">
          <p style={body}>
            When you create a case, we store the observations you submit. An observation is a structural signal — a text description of something that deviates from what its context predicts.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            We do not collect your name, email address, or any identifying information. Cases are created without an account. The only identifier associated with your case is the access code the system generates when you create it. There is no login, no profile, and no personal data attached to your work.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            We collect standard infrastructure logs (request timestamps, IP addresses, error traces). These are retained for up to 30 days for operational purposes and are not linked to case content.
          </p>
        </Section>

        <Section title="How we use it">
          <p style={body}>
            Observations are stored to run your case: scoring them, detecting connections across domains, generating hypotheses. That is the primary use.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            We use structural patterns from observations in aggregate to calibrate and improve the scoring system. This means we study the shapes of what people submit — the structural types, the dimensions that score high or low, the patterns that recur across cases — not the content of individual investigations. No case is read by a person. No observation is attributed to an individual.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            We do not sell data, share data with third parties for commercial purposes, or use observations for advertising of any kind.
          </p>
        </Section>

        <Section title="Your rights">
          <p style={body}>
            You can request deletion of a case and all its observations at any time by contacting us with your access code. We will remove the record entirely within 14 days.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            Because cases carry no personal identifier, we cannot fulfill data subject access requests by name or email — we can only act on requests that include the case access code. If you believe we hold personal data about you outside of a case record, contact us and we will investigate.
          </p>
        </Section>

        <Section title="Third parties">
          <p style={body}>
            Observation processing uses the Anthropic API (Claude) for document extraction, scoring, and hypothesis generation. Observation text is sent to Anthropic's API as part of this processing. Anthropic does not use API-submitted content for training by default. Their privacy policy applies to that processing.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            The application is hosted on Vercel. Infrastructure-level data (logs, request metadata) is subject to Vercel's privacy policy.
          </p>
          <p style={{ ...body, marginTop: '0.9rem' }}>
            We do not use analytics trackers, advertising pixels, or third-party cookies.
          </p>
        </Section>

        <Section title="Research use">
          <p style={body}>
            alvirassa is built on theoretical frameworks under active development. Aggregated structural patterns observed across cases inform that research. Concretely: we study how observations score across dimensions, what types of structural correspondence emerge across domains, and how hypotheses hold or collapse as cases develop. This is research into the method. The content of individual cases is not used.
          </p>
        </Section>

        <Section title="Contact">
          <p style={body}>
            Questions about data, deletion requests, or anything else:{' '}
            <a href="mailto:hello@alvirassa.com" style={{ color: accent, textDecoration: 'none' }}>hello@alvirassa.com</a>
          </p>
        </Section>

      </div>

      <SiteFooter />
    </div>
  )
}
